kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.prometheus.name }}
#  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.prometheus.name }}
roleRef:
  kind: ClusterRole
  name: servicemeshmemberrolls.maistra.io-v1-view
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.prometheus.name }}
  namespace: {{ .Values.istio_control_plane_namespace }} 
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.prometheus.name }}
roleRef:
  kind: ClusterRole
  name: prometheus-istio-system
  apiGroup: rbac.authorization.k8s.io
{{ $params:= . }}  
{{ range $index, $namespace := .Values.members }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $params.Values.prometheus.name }}
  namespace: {{ $namespace }}
subjects:
- kind: ServiceAccount
  namespace: {{ $params.Release.Namespace }}
  name: {{ $params.Values.prometheus.name }}
roleRef:
  kind: ClusterRole
  name: prometheus-istio-system
  apiGroup: rbac.authorization.k8s.io 
{{ end }}