apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ .Values.prometheus.name }}
  labels:
    prometheus: {{ .Values.prometheus.name }}
  namespace: {{ .Release.Namespace }}
spec:
  podMetadata:
    labels:
      maistra.io/expose-route: 'true'
  secrets:
    - prometheus-k8s-tls
    - prometheus-k8s-proxy
  containers:
    - args:
        - '-provider=openshift'
        - '-pass-basic-auth=false'
        - '-https-address=:9091'
        - '-http-address='
        - '-email-domain=*'
        - '-upstream=http://localhost:9090'
        - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
        - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}'
        - '-tls-cert=/etc/tls/private/tls.crt'
        - '-tls-key=/etc/tls/private/tls.key'
        - '-client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token'
        - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
        - '-openshift-service-account=sre-prometheus'
        - '-openshift-ca=/etc/pki/tls/cert.pem'
        - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
        - '-skip-auth-regex=^/metrics'
      image: 'quay.io/openshift/origin-oauth-proxy:4.6'
      name: prometheus-proxy
      ports:
        - containerPort: 9091
          name: proxy
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
      terminationMessagePolicy: FallbackToLogsOnError
      volumeMounts:
        - mountPath: /etc/tls/private
          name: secret-prometheus-k8s-tls
        - mountPath: /etc/proxy/secrets
          name: secret-prometheus-k8s-proxy
  replicas: 2
  serviceAccountName: {{ .Values.prometheus.name }}
  serviceMonitorSelector: {}
  alerting:
    alertmanagers:
    - namespace: {{ .Release.Namespace }}
      name: {{ .Values.alertmanager.name }}
      port: web
  additionalScrapeConfigs:
    name: {{ .Values.prometheus.name }}-additional-scrape-configs
    key: prometheus-additional.yaml
  volumeMounts:
  - name: istio-certs
    mountPath: /etc/istio-certs
  volumes:
  - name: istio-certs
    secret:
      secretName: istio-certs
      defaultMode: 42
  #serviceAccountName: prometheus
  baseImage: registry.redhat.io/openshift-service-mesh/prometheus-rhel8
  sha: 70960efc418688d96d6e9b1ee8a35905ce221cb08d9e5aefff9616e44b95cd9f
  ruleSelector:
    matchLabels: 
      sre-monitoring: "true"
  serviceMonitorSelector: 
    matchLabels: 
      sre-monitoring: "true"
  podMonitorSelector:
    matchLabels:
      sre-monitoring: "true"
  ruleNamespaceSelector:
    matchLabels:
      maistra.io/member-of: {{ .Values.istio_control_plane.namespace }}
  serviceMonitorNamespaceSelector:
    matchLabels:
      maistra.io/member-of: {{ .Values.istio_control_plane.namespace }}
  podMonitorNamespaceSelector:
    matchLabels:
      maistra.io/member-of: {{ .Values.istio_control_plane.namespace }}
