---
alertmanager:
  name: sre-alertmanager
prometheus:
  name: sre-prometheus
grafana:
  name: sre-grafana
prometheus_datasource:
  openshift_monitoring:
    password: "TODO"
  istio_system:
    password: "TODO"
session:
  secret: ciao
istio_control_plane:
  name: basic-install
  namespace: istio-system